Added husky pre-commit script

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,19 +1,19 @@
-
-#!/bin/bash
-# Warn before pushing to protected branches
-# Make script executable with chmod +x pre-push
-# Bypass with git push --no-verify
-
 BRANCH=`git rev-parse --abbrev-ref HEAD`
 PROTECTED_BRANCHES="^(master|dev|testGitHook)"
 
 if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]; then
-  read -p "Are you sure you want to push to \"$BRANCH\" ? (y/n): " -n 1 -r < /dev/tty
-  echo
-  if [[ $REPLY =~ ^[Yy]$ ]]; then
-    exit 0
-  fi
-  echo "Push aborted."
-  exit 1
+
+    if [ -t 1 ]; then
+        read -p "Are you sure you want to push to \"$BRANCH\" ? (y/n): " -n 1 -r < /dev/tty
+        echo
+    if [[ $REPLY =~ ^[Yy]$ ]]; then
+        exit 0
+    fi
+    else
+        echo "You are not allowed to push to \"$BRANCH\"."
+    fi
+
+    echo "Push aborted."
+    exit 1
 fi
 exit 0
